### ISSUE TITLE
TypeError: sassGlob is not a function

### ISSUE THREAD

**Issue by hkirsman** [tomgrooffer/gulp-sass-glob#13]
Running Mac OS/X El Capitan

Code from example:
```
var gulp = require('gulp');
var sass = require('gulp-sass');
var sassGlob = require('gulp-sass-glob');

gulp.task('styles', function () {
  return gulp
    .src('src/styles/main.scss')
    .pipe(sassGlob())
    .pipe(sass())
    .pipe(gulp.dest('dist/styles'));
});
```

Run with 
`gulp styles`

Error message:
```
[15:34:57] Starting 'styles'...
[15:34:57] 'styles' errored after 7.27 ms
[15:34:57] TypeError: sassGlob is not a function
    at Gulp.<anonymous> (/Users/hannes/Sites/apkr/drupal/current/gulpfile.js:8:11)
    at module.exports (/Users/hannes/Sites/apkr/drupal/current/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/hannes/Sites/apkr/drupal/current/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/hannes/Sites/apkr/drupal/current/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/Users/hannes/Sites/apkr/drupal/current/node_modules/orchestrator/index.js:134:8)
    at /usr/local/lib/node_modules/gulp/bin/gulp.js:129:20
    at nextTickCallbackWith0Args (node.js:453:9)
    at process._tickCallback (node.js:382:13)
    at Function.Module.runMain (module.js:449:11)
    at startup (node.js:140:18)

```

package.json
```
{
  "name": "ap",
  "version": "1.0.0",
  "description": "",
  "main": "gulpfile.js",
  "dependencies": {},
  "devDependencies": {
    "gulp": "^3.9.1",
    "gulp-sass": "^2.2.0",
    "gulp-sass-glob": "^1.0.3"
  },
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "repository": {
    "type": "git",
    "url": "git+ssh://git@bitbucket.org/mekaia/handbooks-core.git"
  },
  "author": "",
  "license": "ISC",
  "homepage": "https://bitbucket.org/mekaia/handbooks-core#readme"
}

```

**Comment by marcomag** [comment]
`.pipe(sassGlob.default())` solved the issue for me, but is nowhere to be found in the documentation.

**Comment by tomgrooffer** [comment]
fixed ;) please update the package

**Comment by hkirsman** [comment]
Thank you very much!
